language: cpp
dist: trusty
sudo: required
only:
  - master
  - develop
  - coverity
  - \/feature\/.+
  - \/fix\/.+
  - \/hotfix\/.+
  - \/release\/.+

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libssl-dev
    - libbluetooth3
    - libbluetooth-dev
    - libudev-dev
    - cmake
    - html2text
    - clang-format-3.6
  coverity_scan:
    project:
      name: "smartdevicelink/sdl_core"
      description: "Build submitted via Travis CI"
    notification_email: jack@livio.io
    build_command_prepend: "mkdir build && cd build && cmake ../"
    build_command:   "make install"
    branch_pattern: coverity
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -q -y install libavahi-client-dev bluez-tools sqlite3 libsqlite3-dev automake1.11
  - wget http://archive.ubuntu.com/ubuntu/pool/main/l/lcov/lcov_1.11-3_all.deb
  - sudo dpkg -i lcov_1.11-3_all.deb
script:
  - sudo ln -sf /usr/bin/gcov-4.9 /usr/bin/gcov
  - bash -e tools/infrastructure/check_style.sh
  - mkdir build && cd build && cmake ../ -DBUILD_TESTS=ON -DENABLE_GCOV=ON && make install
  - sudo ldconfig
  - make test
  - bash -ex ../tools/infrastructure/collect_coverage.sh ./
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - CTEST_OUTPUT_ON_FAILURE=TRUE
  - CMAKE_CXX_COMPILER=g++-4.9
  - CMAKE_C_COMPILER=gcc-4.9
  - LD_LIBRARY_PATH=.
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "gGRieQzK0ExcuQRaMs/8mbXK4gitDSBs9RFV/iIqVUeKv+1ZyA4UP4tGAFXeY8Kl0sbRtld7t03Wx1/u0JI1bON2XMn/wCj0Hr8kbwt3eJr1bpG8dVr0tqDpfYVsBjX/nMxwNNBillvBpyXRoZf8z7ukZJAyRMMVG5tHqUVJM4k="
after_success:
  - pwd ; bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage.info || echo "Codecov did not collect coverage reports"
deploy:
  provider: releases
  api-key: "uw8e4USTAS6c9LFhRMYOvw"
  file:
    - "coverage_report.tar.gz"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    - AKutsan@luxoft.com
    - AByzhynar@luxoft.com
    - NSnitsar@luxoft.com
    - RMalynovskyi@luxoft.com
    - MGhiumiusliu@luxoft.com
    - AGaliuzov@luxoft.com
    - ANosach@luxoft.com

